name: Node.js CI

on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        CI: false
        PUBLIC_URL: https://akiraro.github.io/MovieSearchEngine/
        REACT_APP_APIKey: ${{ secrets.REACT_APP_APIKEY }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        CI: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
